name: Build

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install dependencies
        run: |
          sudo apt-get update -qq && sudo apt-get -y install \
          cmake
 
      - name: Build xevd
        run: |
          mkdir build
          cd build
          cmake ..
          make
          
      - name: 'Upload executable Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: xevd_app-linux
          path: build/bin/xevd_app
          retention-days: 5
          
      - name: 'Upload library Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: libxevd-linux
          path: build/lib/
          retention-days: 5

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build xevd
        run: |
          mkdir build
          cd build
          cmake .. -G "MinGW Makefiles"
          make
          
      - name: 'Upload executable Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: xevd_app-windows
          path: build/bin/xeved_app.exe
          retention-days: 5

      - name: 'Upload library Artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: libxevd-windows
          path: build/src/libxevd.*
          retention-days: 5
