name: Release packages
on:
  release:
    types: [published]

  workflow_dispatch:

jobs:

  # Matrix job - Create packages and attach them to latest release assets.
  make-package:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install dependencies (Linux)
        if: ${{matrix.os == 'ubuntu-latest'}}
        run: |
          sudo apt-get update -qq && sudo apt-get -y install \
          cmake
        
      - name: Build Linux versions of xevd, generate packages and md5
        if: ${{matrix.os == 'ubuntu-latest'}}
        run: |
          mkdir build
          cd build
          cmake .. -DBUILD_TYPE=Release
          make
          make package

      - name: Build Windows versions of xevd, generate packages and md5
        if: ${{matrix.os == 'windows-latest'}}
        run: |
          mkdir build
          cd build
          cmake .. -G "MinGW Makefiles" -DBUILD_TYPE=Release
          make
          make package

      - name: 'Upload Linux artifacts'
        if: ${{matrix.os == 'ubuntu-latest'}}
        uses: actions/upload-artifact@v3
        with:
          name: xevd-linux-packages-${{ github.event.release.tag_name }}
          path: |
            ${{ github.workspace }}/build/*.deb
            ${{ github.workspace }}/build/*.md5
          retention-days: 7

      - name: 'Upload Windows artifacts'
        if: ${{matrix.os == 'windows-latest'}}
        uses: actions/upload-artifact@v3
        with:
          name: xevd-windows-packages-${{ github.event.release.tag_name }}
          path: |
            ${{ github.workspace }}/build/*.exe
            ${{ github.workspace }}/build/*.md5
          retention-days: 7

      - name: Upload assets to GitHub Release
        uses: xresloader/upload-to-github-release@v1.3.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "build/*.deb; build/*.exe; build/*.md5"
          update_latest_release: true
          draft: false
          overwrite: true
